### ISSUE TITLE
example server implementation in README needs adjustments

### ISSUE THREAD

**Issue by DirkDuesentrieb** [cgrates/radigo#1]
The NewServer() and NewClient() functions need an additional parameter "Coder" eg from NewCoder() or nil.

The packet of the client request does not need to be created manually if you have NewRequest() and AddAVPWithName() for this.

There is some t.Error stuff from testing that should be log.Fatalln() or similar

**Comment by danbogos** [comment]
hey @DirkDuesentrieb 

You can find latest code initialization here:
https://github.com/cgrates/cgrates/blob/master/agents/radagent.go#L45

I would appreciate if you correct the README here in the way you consider useful and do a PR.

Many thanks!

DanB
