### ISSUE TITLE
password decoding unclear

### ISSUE THREAD

**Issue by DirkDuesentrieb** [cgrates/radigo#3]
The original project had a function DecodeUserPassword() in [validation.go](https://github.com/jessta/radius/blob/master/validation.go). The validation was half done but the password part functional. I tried to to find a part like this in your fork, but couldn't find it. It seems like it should be part of your [coder](https://github.com/cgrates/radigo/blob/master/coder.go), but you need the shared secret of the connecting instance for decoding - and I think you don't have access to the Secrets struct to use GetSecret() within a codec. What would be your approach to decode the users password?

**Comment by danbogos** [comment]
hey @DirkDuesentrieb 

Will come back on this one since we have a project interested about functionality  and will share the solution after we implement it (let's say 2 weeks window time).

Thanks,
DanB

**Comment by danbogos** [comment]
Should be implemented in  master.
